### ISSUE TITLE
Error path format incoherent

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/ex_component_schema#7]
The error path format does not use one format, sometimes it will start with `#` sometimes with `/root`.
Because of that, we had to find an alternative to get the correct error path from the application_runner repository as we can see on the following link: 
https://github.com/lenra-io/application-runner/pull/12/files#diff-678ebfc68a870921dc59538a65ff327f1f26e1d002d2e4d67f63c26c77c860d3R168

PR link https://github.com/lenra-io/application-runner/pull/12

**Comment by jonas-martinez** [comment]
We decided IRL with @Nesqwik that it was not a problem

**Comment by Nesqwik** [comment]
The error path should now always start with `# `referencing the "base" node in the UI tree.
